### ISSUE TITLE
maybe explore hooks vs classes for 20s more.  this is a tough one. generally prefer classes and dislike hooks but

### ISSUE THREAD

**Issue by timofei7** [dartmouth-cs52/dartmouth-cs52.github.io#217]
but maybe come up with a nice intro that simplifies this

**Comment by tmonfre** [comment]
happy to work on this if you'd like

having used hooks a bit, I think they are useful for smaller components that are, for all intents and purposes, supposed to be stateless, but need a single state variable or two. a good example is an `<input />` field where a state variable is used to store what the user types and is set on the `onChange` callback. I think it's a bit annoying to have to create an entire class for this.

for a bigger component that is stateful and holds a lot of data, I think hooks sort of fail to be useful and classes are then better. but overall functional components are supposed to be faster, are easier to test, and personally I think are easier to read. so preserving their use as much as possible w hooks might not be a bad thing

**Comment by timofei7** [comment]
@tmonfre  sure - what are you thinking, like a short assignment on it or?   i thought i had a few slides about it but looks like i never did that last year - so could be a short part of lecture, or if you wanted to give a tutorial on them during class?

**Comment by tmonfre** [comment]
would love to do an in-class tutorial but unfortunately have a 2A that is meeting live over zoom. I can definitely add some slides for the basics of hooks (i.e. just the state hook). I could also make a short for all hooks (effect hook, build your own, etc), but it would probably be on the shorter side unless we combine it with something else. thoughts?
