### ISSUE TITLE
deprecated installation for custom git prompts in SA1

### ISSUE THREAD

**Issue by isabellahoch** [dartmouth-cs52/dartmouth-cs52.github.io#310]
I wasn't sure how to submit this feedback directly through GitHub so thought creating an issue might be best! Please let me know if it would be easier for me to send this through Slack or somewhere else.
As I was working through the [Local Dev Assignment (Line 54)](https://github.com/dartmouth-cs52/dartmouth-cs52.github.io/blob/main/assignments/sa/localdev/index.md#L54), I tried cloning the [repo](https://github.com/jimeh/git-aware-prompt) to make my life easier with git, but kept running into the same issue: ```console fatal: remote error:    
 The unauthenticated git protocol on port 9418 is no longer supported.```     
I looked into it, and it appears to be because GitHub isn't supporting unencrypted protocols anymore; perhaps on the assignment page you can suggest cloning the repo through GitHub Desktop or using [HTTPS](https://github.com/jimeh/git-aware-prompt.git) ([https://github.com/jimeh/git-aware-prompt.git](https://github.com/jimeh/git-aware-prompt.git)) as I did to avoid this error (although maybe I should be raising an issue on @jimeh's original repo instead of here!)
This isn't a huge problem as I'm not sure how many people will want to make git easier, but I thought it wouldn't hurt to bring it to your attention.

**Comment by timofei7** [comment]
great idea to post this as an issue on that original issue,  they don’t support git:// anymore but prefer ***@***.***:// syntax

thanks for raising it!

Cheers,
Tim
